name: "godot-ci export"
on: push

env:
  # https://hub.docker.com/r/barichello/godot-ci/tags
  GODOT_VERSION: 3.5
  DOCKER_IMAGE: barichello/godot-ci:3.5
  PROJECT_FOLDER: demo_project

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: '${DOCKER_IMAGE}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_FOLDER
          godot -v --export "HTML5" ../build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: build/web

      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.
